adding changes made during initial attempt to run PUP on ADNI scans

diff --git a/scripts/petpreproc b/scripts/petpreproc
--- a/scripts/petpreproc
+++ b/scripts/petpreproc
@@ -16,7 +16,8 @@
 #		format = 0 (DICOM) 					       #
 #		format = 1 (ecat)					       #
 #		format = 2 (Siemens InterFile)                                 #
-#	        format = 5 (nih nifti format)				       #
+#	        format = 5 (nih nifti format)                                  #
+#		format = 6 (Gzipped Nifti format)		               #                                #
 #	filterxy: fwhm of in-plane filtering				       #
 #	filterz:  fwhm of axial filtering				       #
 #                                                                              #
@@ -67,6 +68,9 @@ then
 elif (( $format == 5 ))
 then
 	nih_4dfp $petdir/$petfn $petid $half_life || die "$program ERROR: nih_4dfp $petdir/$petfn $petid $halflife failed"
+elif (( $format == 6 ))
+then
+	niftigz_4dfp -4 $petdir/$petfn $petid || die "$program ERROR: niftigz_4dfp -4 $petdir/$petfn failed"
 fi
 # Generate .info file
 PETinfo $petid $format $delay || die "$program ERROR: PETinfo $petid $format $delay failed"
@@ -93,44 +97,44 @@ then
 fi
 rm ${petid}_sumall.4dfp.*
 
-# Filtering if requested
-if [ -n "$filterxy" ] && [ -n "$filterz" ]
-then
-	if [ "$filterxy" != "$filterz" ]
-	then
-		tmp=$(echo "scale=6; $filterxy*10+.499999" | bc)
-		filterxyname=${tmp%.*}
-		tmp=$(echo "scale=6; $filterz*10+.499999" | bc)
-		filterzname=${tmp%.*}
-		imgblur_4dfp -xy $petid $filterxy || die "$program ERROR: imgblur_4dfp -xy $petid $filterxy failed"
-		imgblur_4dfp -z ${petid}_bxy$filterxyname $filterz || die "$program ERROR: imgblur_4dfp -z ${petid}_bxy$filterxyname $filterz failed"
-
-		ext=( img img.rec ifh hdr )
-		for (( i=0; i<4; i++ ))
-		do
-			cp ${petid}_bxy${filterxyname}_bz${filterzname}.4dfp.${ext[$i]} ${petid}n.4dfp.${ext[$i]}
-		done
-		rm ${petid}_bxy$filterxyname.4dfp.*
-		rm ${petid}_bxy${filterxyname}_bz${filterzname}.4dfp.*
-	else
-		tmp=$(echo "scale=6; $filterxy*10+.499999" | bc)
-		filtername=${tmp%.*}
-		imgblur_4dfp ${petid} $filterxy || die "$program ERROR: imgblur_4dfp ${petid} $filterxy failed"
-		ext=( img img.rec ifh hdr )
-		for (( i=0; i<4; i++ ))
-		do
-			cp ${petid}_b${filtername}.4dfp.${ext[$i]} ${petid}n.4dfp.${ext[$i]}
-		done
-		rm ${petid}_b${filtername}.4dfp.*
-	fi
-	cp ${petid}.info ${petid}n.info
-	petid=${petid}n
-	echo "petid=${petid}" >> $paramsfn
-elif [ -n "$filterxy" ] || [  -n "$filterz" ]
-then
-	ERR="Both xy and z filter size are needed!"
-	echo $ERR
-	die "$program ERROR: $ERR"
-fi
+## Filtering if requested
+#if [ -n "$filterxy" ] && [ -n "$filterz" ]
+#then
+#	if [ "$filterxy" != "$filterz" ]
+#	then
+#		tmp=$(echo "scale=6; $filterxy*10+.499999" | bc)
+#		filterxyname=${tmp%.*}
+#		tmp=$(echo "scale=6; $filterz*10+.499999" | bc)
+#		filterzname=${tmp%.*}
+#		imgblur_4dfp -xy $petid $filterxy || die "$program ERROR: imgblur_4dfp -xy $petid $filterxy failed"
+#		imgblur_4dfp -z ${petid}_bxy$filterxyname $filterz || die "$program ERROR: imgblur_4dfp -z ${petid}_bxy$filterxyname $filterz failed"
+#
+#		ext=( img img.rec ifh hdr )
+#		for (( i=0; i<4; i++ ))
+#		do
+#			cp ${petid}_bxy${filterxyname}_bz${filterzname}.4dfp.${ext[$i]} ${petid}n.4dfp.${ext[$i]}
+#		done
+#		rm ${petid}_bxy$filterxyname.4dfp.*
+#		rm ${petid}_bxy${filterxyname}_bz${filterzname}.4dfp.*
+#	else
+#		tmp=$(echo "scale=6; $filterxy*10+.499999" | bc)
+#		filtername=${tmp%.*}
+#		imgblur_4dfp ${petid} $filterxy || die "$program ERROR: imgblur_4dfp ${petid} $filterxy failed"
+#		ext=( img img.rec ifh hdr )
+#		for (( i=0; i<4; i++ ))
+#		do
+#			cp ${petid}_b${filtername}.4dfp.${ext[$i]} ${petid}n.4dfp.${ext[$i]}
+#		done
+#		rm ${petid}_b${filtername}.4dfp.*
+#	fi
+#	cp ${petid}.info ${petid}n.info
+#	petid=${petid}n
+#	echo "petid=${petid}" >> $paramsfn
+#elif [ -n "$filterxy" ] || [  -n "$filterz" ]
+#then
+#	ERR="Both xy and z filter size are needed!"
+#	echo $ERR
+#	die "$program ERROR: $ERR"
+#fi
 
 
diff --git a/scripts/petproc b/scripts/petproc
--- a/scripts/petproc
+++ b/scripts/petproc
@@ -64,32 +64,32 @@ petreg $paramsfn || die "$program ERROR: PET to target registration failed"
 
 ###############################################################################
 # Determine model frames
-petmdlframes $paramsfn || die "$program ERROR: Model Frames failed"
+#petmdlframes $paramsfn || die "$program ERROR: Model Frames failed"
 
 ###############################################################################
 # Full Kinetic Processing
 
 # ROI TAC extraction
-petroitac $paramsfn || die "$program ERROR: ROI TAC extraction failed"
+#petroitac $paramsfn || die "$program ERROR: ROI TAC extraction failed"
 
 # Logan Reference Region Analysis
-if [ "$model" = "logan" ]
-then
-	petrefroi $paramsfn || die "$program ERROR: REF TAC extraction failed"
-	petroiloganREF $paramsfn || die "$program ERROR: Logan Reference Region Analysis failed"
-	petloganrep $paramsfn || die "$program ERROR: petloganrep failed"
-fi
+#if [ "$model" = "logan" ]
+#then
+#	petrefroi $paramsfn || die "$program ERROR: REF TAC extraction failed"
+#	petroiloganREF $paramsfn || die "$program ERROR: Logan Reference Region Analysis failed"
+#	petloganrep $paramsfn || die "$program ERROR: petloganrep failed"
+#fi
 # Additional analysis will be implemented in the future
 
 ###############################################################################
 # Static Processing
 
-if [ "$suvr" = "1" ]
-then
-	petmdlsum $paramsfn || die "$program ERROR: petmdlsum failed"
-	petroiint $paramsfn || die "$program ERROR: Static ROI intensity extraction failed"
-	petrefroi $paramsfn || die "$program ERROR: petrefroi failed"
-	petsuvr $paramsfn || die "$program ERROR: SUVR Analysis failed"
-	petsuvrrep $paramsfn || die "$program ERROR: SUVR Analysis failed"
-fi
+#if [ "$suvr" = "1" ]
+#then
+#	petmdlsum $paramsfn || die "$program ERROR: petmdlsum failed"
+#	petroiint $paramsfn || die "$program ERROR: Static ROI intensity extraction failed"
+#	petrefroi $paramsfn || die "$program ERROR: petrefroi failed"
+#	petsuvr $paramsfn || die "$program ERROR: SUVR Analysis failed"
+#	petsuvrrep $paramsfn || die "$program ERROR: SUVR Analysis failed"
+#fi
 
diff --git a/scripts/targpreproc b/scripts/targpreproc
--- a/scripts/targpreproc
+++ b/scripts/targpreproc
@@ -41,10 +41,10 @@ source $paramsfn || die "$program ERROR: Cannot source params file $paramsfn"
 
 # FREESURFER based processing. The preprocessing step converts freesurfer
 # files into 4dfp format, and prepares for ROI analysis.
-if (( FS == 1 ))
-then
-	fspreproc $paramsfn || die "$program ERROR: fspreproc $paramsfn failed"
-fi
+#if (( FS == 1 ))
+#then
+#	fspreproc $paramsfn || die "$program ERROR: fspreproc $paramsfn failed"
+#fi
 
 # PET ATLAS based processing. The preprocessing step populates PET atlas
 # template image and ROI definetion files in the PET atlas space and prepare
